import = [
       "~/.config/alacritty/themes/gruvbox_dark.toml"
]


[shell]
program = "/usr/bin/zsh"

[window]
padding = { x = 5, y = 5 }
dynamic_padding = false
opacity = 1

[font]
normal = { family = "IosevkaLyteTerm Nerd Font", style = "Regular" }
bold = { family = "IosevkaLyteTerm Nerd Font", style = "Bold" }
italic = { family = "IosevkaLyteTerm Nerd Font", style = "Oblique" }
bold_italic = { family = "IosevkaLyteTerm Nerd Font", style = "Bold Italic" }
size = 12

[cursor]
style = { shape = "Block", blinking = "Always" }
thickness = 0.5
