;;; memory-usage-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from memory-usage.el

(autoload 'memory-usage "memory-usage" "\
List all buffers and their memory usage." t)
(register-definition-prefixes "memory-usage" '("memory-usage-"))

;;; End of scraped data

(provide 'memory-usage-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; memory-usage-autoloads.el ends here
