;;; avy-zap-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from avy-zap.el

(autoload 'avy-zap-to-char "avy-zap" "\
Zap to char using `avy'." t)
(autoload 'avy-zap-to-char-dwim "avy-zap" "\
Without PREFIX, call `avy-zap-to-char'.
With PREFIX, call `zap-to-char'.

(fn &optional PREFIX)" t)
(autoload 'avy-zap-up-to-char "avy-zap" "\
Zap up to char using `avy'." t)
(autoload 'avy-zap-up-to-char-dwim "avy-zap" "\
Without PREFIX, call `avy-zap-up-to-char'.
With PREFIX, call `zap-up-to-char'.

(fn &optional PREFIX)" t)
(register-definition-prefixes "avy-zap" '("avy-zap-"))

;;; End of scraped data

(provide 'avy-zap-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; avy-zap-autoloads.el ends here
