;;; esh-help-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from esh-help.el

(autoload 'setup-esh-help-eldoc "esh-help" "\
Setup eldoc function for Eshell." t)
(autoload 'esh-help-run-help "esh-help" "\
Show help for the pointed command or functions CMD.
It comes from Zsh.

(fn CMD)" t)
(register-definition-prefixes "esh-help" '("esh-help-"))

;;; End of scraped data

(provide 'esh-help-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; esh-help-autoloads.el ends here
