;;; atomic-chrome-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from atomic-chrome.el

(autoload 'atomic-chrome-start-server "atomic-chrome" "\
Start websocket server for atomic-chrome.
Fails silently if a server is already running." t)
(autoload 'atomic-chrome-stop-server "atomic-chrome" "\
Stop websocket server for atomic-chrome." t)
(register-definition-prefixes "atomic-chrome" '("atomic-chrome-" "global-atomic-chrome-edit-mode"))

;;; End of scraped data

(provide 'atomic-chrome-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; atomic-chrome-autoloads.el ends here
