;;; gh-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gh-api.el

(register-definition-prefixes "gh-api" '("gh-" "initialize-instance" "logito-log"))


;;; Generated autoloads from gh-auth.el

(register-definition-prefixes "gh-auth" '("gh-" "initialize-instance"))


;;; Generated autoloads from gh-cache.el

(register-definition-prefixes "gh-cache" '("gh-cache" "pcache-"))


;;; Generated autoloads from gh-comments.el

(register-definition-prefixes "gh-comments" '("gh-comments-"))


;;; Generated autoloads from gh-common.el

(register-definition-prefixes "gh-common" '("gh-" "slot-unbound"))


;;; Generated autoloads from gh-gist.el

(register-definition-prefixes "gh-gist" '("constructor" "gh-gist-"))


;;; Generated autoloads from gh-issues.el

(register-definition-prefixes "gh-issues" '("gh-issues-"))


;;; Generated autoloads from gh-oauth.el

(register-definition-prefixes "gh-oauth" '("gh-oauth-" "initialize-instance"))


;;; Generated autoloads from gh-orgs.el

(register-definition-prefixes "gh-orgs" '("gh-orgs-"))


;;; Generated autoloads from gh-profile.el

(register-definition-prefixes "gh-profile" '("gh-profile-"))


;;; Generated autoloads from gh-pulls.el

(register-definition-prefixes "gh-pulls" '("gh-pulls-"))


;;; Generated autoloads from gh-repos.el

(register-definition-prefixes "gh-repos" '("gh-repos-"))


;;; Generated autoloads from gh-search.el

(register-definition-prefixes "gh-search" '("gh-search-"))


;;; Generated autoloads from gh-url.el

(register-definition-prefixes "gh-url" '("gh-url-"))


;;; Generated autoloads from gh-users.el

(register-definition-prefixes "gh-users" '("gh-users-"))

;;; End of scraped data

(provide 'gh-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gh-autoloads.el ends here
