;;; lsp-sourcekit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lsp-sourcekit.el

(autoload 'lsp-sourcekit--find-executable-with-xcrun "lsp-sourcekit" "\
sourcekit-lsp may be installed behind xcrun; if we can't find
the `lsp-sourcekit-executable' on PATH, try it with xcrun.")
(with-eval-after-load 'lsp-mode (lsp-dependency 'sourcekit-lsp (list :system 'lsp-sourcekit-executable) (list :system #'lsp-sourcekit--find-executable-with-xcrun)) (lsp-register-client (make-lsp-client :new-connection (lsp-stdio-connection (lambda nil (cons lsp-sourcekit-executable lsp-sourcekit-extra-args))) :major-modes '(swift-mode) :server-id 'sourcekit-ls)))
(register-definition-prefixes "lsp-sourcekit" '("lsp-sourcekit-ex"))

;;; End of scraped data

(provide 'lsp-sourcekit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lsp-sourcekit-autoloads.el ends here
