import = ["~/.config/alacritty/themes/rose-pine.toml"]

[shell]
program = "/usr/bin/tmux"

[window]
padding = { x = 2, y = 2 }

[font]
normal = { family = "XD", style = "Semibold" }
bold = { family = "XD", style = "Bold" }
italic = { family = "XD", style = "Oblique" }
bold_italic = { family = "XD", style = "Bold Oblique" }
size = 12.0
