import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[shell]
program = "/usr/bin/zsh"

[window]
padding = { x = 2, y = 2 }

[font]
normal = { family = "IosevkaLyteTerm", style = "Regular" }
bold = { family = "IosevkaLyteTerm", style = "Bold" }
italic = { family = "IosevkaLyteTerm", style = "Book" }
bold_italic = { family = "Iosevka Nerd Font", style = "Bold Oblique" }

size = 12.0
offset.x = 0
offset.y = 2

