import = [
    "~/.config/alacritty/themes/modus_vivendi.toml"
]

[shell]
program = "/usr/bin/tmux"

[window]
padding = { x = 2, y = 2 }

[font]
normal = { family = "VictorMono Nerd Font", style = "Regular" }
bold = { family = "VictorMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Book" }
bold_italic = { family = "VictorMono Nerd Font", style = "Bold Oblique" }
size = 10.0
