import = ["~/.config/alacritty/themes/modus_vivendi.toml"]

[shell]
program = "/usr/bin/tmux"

[window]
padding = { x = 2, y = 2 }

[font]
normal = { family = "XD", style = "Regular" }
bold = { family = "XD", style = "Bold" }
italic = { family = "XD", style = "Book" }
bold_italic = { family = "XD", style = "Bold Oblique" }
size = 14.0
