import = []

[shell]
program = "/usr/bin/zsh"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9

[font]
normal = { family = "IosevkaLyteTerm Nerd Font", style = "Regular" }
bold = { family = "IosevkaLyteTerm Nerd Font", style = "Bold" }
italic = { family = "IosevkaLyteTerm Nerd Font", style = "Oblique" }
bold_italic = { family = "IosevkaLyteTerm Nerd Font", style = "Bold Italic" }
size = 16

[cursor]
style = { shape = "Beam", blinking = "Always" }

